### ISSUE TITLE
Collapse Compaction coordinator code into the Manager

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#4220]
In elasticity, the coordinator has been collapsed into the manager to reduce complexity around running number of different accumulo servers.

As we have standardized on using external compactions and deprecated internal compactions in `3.1`, we should also migrate the coordinator code into the manager.

This should also replace the top level `compaction` entry from the cluster.yaml with `compactor` 
```
compactor:
    - q1:
        - localhost1
        - localhost2
    - q2:
        - localhost3
        - localhost4
```
