### ISSUE TITLE
Set compactors_per_host on a per queue basis

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#4424]
**Is your feature request related to a problem? Please describe.**
There is a desire to configure a different number of compactors per defined queue. 
Add the ability to the cluster.yaml to define the number of compactors per host on a per-queue basis.  

**Describe the solution you'd like**
Define the number of desired compactors per host under each queue section in the cluster.yaml.

```
  compactor:
    - q1:
        compactors_per_host: 2
        - localhost1
        - localhost2
    - q2:
        compactors_per_host: 1
        - localhost1
        - localhost2        
```

**Comment by dlmarion** [comment]
I think the script may support this in a rudimentary way (but I have not tested this). A top level `compactors_per_host` setting was added in #4329. I wonder if using different hostnames in the lists would allow you to start multiples of that setting. For example:

```
  compactor:
    - q1:
        - localhost
    - q2:
        - localhost
        - 127.0.0.1
    - q3:
        - localhost
        - localhost.localdomain
        - 127.0.0.1
...
  compactors_per_host: 1        
```

I'm curious if that would satisfy your need. I'm wary of making the `accumulo-cluster` script some full-blown cluster management solution.

**Comment by keith-turner** [comment]
Another way this could be done is by making the information parallel.

```yaml

  compactor:
    - q1:
      - localhost1
      - localhost2
    - q2:
      - localhost1
      - localhost2 
    - q3:
      - localhost1
      - localhost2 

compactors_per_host: 1
   -q1: 5
   -q2: 2
```

In the above example q3 would have 1 compactor per host, q1 5 compactors per host, and q2 2 compactors per host.  The drawback of this approach is that runtime checks and errors are needed to ensure consistency of queue names specified in two places.  Only suggested this because it seems easier to implement from a compatibility standpoint.

**Comment by keith-turner** [comment]
Could we optionally add a struct after  a queue name?  Looking at the yaml spec, seems like this could be done.  But not sure if its needed everywhere then. Using a struct allows adding more field in the future.


```yaml
  compactor:
    - q1: {compactors_per_host: 5}
      - localhost1
      - localhost2
    - q2: {compactors_per_host: 2} 
      - localhost1
      - localhost2 
    - q3:
      - localhost1
      - localhost2 

compactors_per_host: 1
```
